CREATE TABLE USERS (
  ID VARCHAR(4) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ADMIN_CODE integer default 0,
  CREATED_AT timestamp default CURRENT_TIMESTAMP,
  UPDATED_AT timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ADMIN_CODE) VALUES
('0001', 'admin', 'admin@example.com','test1234', 1);



CREATE TABLE WORKS (
  ID  SERIAL NOT NULL,
  USER_ID VARCHAR(4) NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  START_DATE DATE NOT NULL,
  START_TIME TIME NOT NULL,
  END_DATE DATE NOT NULL,
  END_TIME TIME NOT NULL,
  CREATED_AT timestamp default CURRENT_TIMESTAMP,
  UPDATED_AT timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
